name: Docker Image CI

on:
  push:
    branches: [ "master" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapp:latest
      
    - name: login
      run:  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD}}

    - name: push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simpleapp:latest 

      
